# Улучшенная архитектура для генерации 3D моделей
experiment_name: "enhanced_text_to_3d"
seed: 42
device: "cuda"
log_dir: "logs"
checkpoint_dir: "checkpoints"

# Параметры данных
data:
  dataset_name: "ModelNet40"
  dataset_path: "data/ModelNet40"
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1
  batch_size: 4
  num_workers: 4
  voxel_resolution: 64  # Увеличенное разрешение воксельной сетки
  text_max_length: 77
  augmentation: True
  pin_memory: True

# Параметры модели
model:
  text_encoder:
    type: "CLIPWithProjection"  # Улучшенный текстовый энкодер
    pretrained: True
    freeze: False  # Разморозим для тонкой настройки
    embedding_dim: 768  # Увеличенная размерность эмбеддинга
    model_name: "openai/clip-vit-large-patch14"  # Более мощная модель CLIP
  
  shape_generator:
    type: "ImprovedVoxelTransformer"  # Улучшенный генератор форм
    latent_dim: 768  # Согласовано с размерностью эмбеддинга
    hidden_dims: [512, 256, 128, 64, 32]  # Улучшенная архитектура декодера
    dropout: 0.1
    num_heads: 12  # Увеличено число голов внимания
    num_layers: 8  # Увеличена глубина сети
    voxel_dim: 64  # Согласовано с разрешением воксельной сетки
    use_conditional_attention: True  # Новая возможность: условное внимание
    residual_connections: True  # Добавлены остаточные соединения
    normalization: "layer_norm"  # Использование нормализации слоев
    activation: "gelu"  # Улучшенная функция активации

# Параметры обучения
training:
  num_epochs: 5  # Увеличено число эпох
  learning_rate: 0.0001
  weight_decay: 0.0001
  lr_scheduler:
    type: "cosine"
    warmup_epochs: 10
  use_mixed_precision: True
  clip_grad_norm: 1.0
  save_interval: 5
  evaluate_interval: 2
  early_stopping:
    patience: 15  # Увеличено терпение для ранней остановки
    min_delta: 0.001
  accumulation_steps: 8
  curriculum_learning: True  # Добавлено обучение с нарастающей сложностью

# Параметры функции потерь
loss:
  bce_weight: 1.0  # Базовая потеря для воксельной сетки
  l1_weight: 0.1  # Потеря L1 для регуляризации
  perceptual_weight: 0.5  # Добавлена перцептивная потеря
  adversarial_weight: 0.2  # Добавлена состязательная потеря
  chamfer_weight: 0.3  # Добавлена потеря Чемфера для точечного облака

# Параметры оценки
evaluation:
  metrics: ["chamfer_distance", "iou", "f_score", "perceptual_quality"]
  visualization:
    num_samples: 5
    output_dir: "visualizations"
    render_mode: "high_quality"  # Улучшенный рендеринг

# Логирование
logging:
  wandb:
    use: False
    project: "enhanced_text_to_3d"
    entity: "your_entity"
  tensorboard:
    use: True
  memory_tracking: True

# Оптимизация
optimization:
  empty_cache_frequency: "batch"
  optimize_memory: True
  gradient_checkpointing: True
  
# Инференс
inference:
  post_processing:
    mesh_smoothing: True  # Сглаживание меша после генерации
    remeshing: True  # Повторное построение меша для улучшения топологии
    hole_filling: True  # Заполнение дыр в меше
  multi_resolution: True  # Генерация на нескольких разрешениях 