# General settings
experiment_name: "text_to_3d_modelnet40_inference"
seed: 42
device: "cpu"  # Используем CPU для инференса
log_dir: "logs"
checkpoint_dir: "checkpoints"

# Data parameters
data:
  dataset_name: "ModelNet40"
  dataset_path: "data/ModelNet40"
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1
  batch_size: 1  # Для инференса используем batch_size=1
  num_workers: 1
  voxel_resolution: 20
  text_max_length: 77
  augmentation: False
  pin_memory: False

# Model parameters - размеры соответствуют обученной модели в чекпоинте
model:
  text_encoder:
    type: "CLIP"
    pretrained: True
    freeze: True
    embedding_dim: 256  # В чекпоинте используется 256
  
  shape_generator:
    type: "VoxelTransformer"
    latent_dim: 256    # В чекпоинте используется 256
    hidden_dims: [256, 128, 64, 32, 16]  # Размеры из чекпоинта
    dropout: 0.2
    num_heads: 4
    num_layers: 2      # В чекпоинте только 2 слоя
    voxel_dim: 20

# Training parameters (не используются при инференсе, но нужны для загрузки модели)
training:
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.0001
  lr_scheduler:
    type: "cosine"
    warmup_epochs: 5
  use_mixed_precision: False
  clip_grad_norm: 1.0

# Loss parameters
loss:
  bce_weight: 1.0
  l1_weight: 0.1

# Evaluation metrics
evaluation:
  metrics: ["iou"]
  visualization:
    num_samples: 1
    output_dir: "visualizations"

# Logging
logging:
  wandb:
    use: False
  tensorboard:
    use: False
  memory_tracking: False 