device: cuda
log_dir: logs
checkpoint_dir: checkpoints
seed: 42
experiment_name: test
data:
  dataset_path: ../data/ModelNet40
  batch_size: 16
  num_workers: 4
  voxel_resolution: 64
  text_max_length: 77
  augmentation: true
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1
evaluation:
  visualization:
    output_dir: visualizations
