# General settings
experiment_name: "text_to_3d_modelnet40"
seed: 42
device: "cuda"
log_dir: "logs"
checkpoint_dir: "checkpoints"

# Data parameters
data:
  dataset_name: "ModelNet40"
  dataset_path: "/content/drive/My Drive/ModelNet40"
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1
  batch_size: 16
  num_workers: 4
  voxel_resolution: 64
  text_max_length: 77
  augmentation: True

# Model parameters
model:
  text_encoder:
    type: "CLIP"
    pretrained: True
    freeze: False
    embedding_dim: 512
  
  shape_generator:
    type: "VoxelTransformer"
    latent_dim: 512
    hidden_dims: [1024, 512, 256, 128, 64]
    dropout: 0.1
    num_heads: 8
    num_layers: 6
    voxel_dim: 64

# Training parameters
training:
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.0001
  lr_scheduler:
    type: "cosine"
    warmup_epochs: 5
  use_mixed_precision: True
  clip_grad_norm: 1.0
  save_interval: 5
  evaluate_interval: 1
  early_stopping:
    patience: 10
    min_delta: 0.001

# Evaluation metrics
evaluation:
  metrics: ["chamfer_distance", "iou", "f_score"]
  visualization:
    num_samples: 5
    output_dir: "visualizations"

# Logging
logging:
  wandb:
    use: False
    project: "text_to_3d"
    entity: "your_entity"
  tensorboard:
    use: True 