# Конфигурация модели text300M

# Тип модели
model_type: "text300M"

# Параметры модели
input_channels: 3          # Количество входных каналов (xyz)
output_channels: 3         # Количество выходных каналов
n_ctx: 2048                # Максимальное количество точек (уменьшено с 4096)
width: 256                 # Размерность скрытых слоев (уменьшено с 512)
layers: 6                  # Количество слоев трансформера (уменьшено с 12)
heads: 4                   # Количество голов внимания (уменьшено с 8)
dropout: 0.1               # Коэффициент dropout
text_embed_dim: 256        # Размерность текстовых эмбеддингов (уменьшено с 512)

# Параметры обучения
learning_rate: 1e-4        # Скорость обучения
weight_decay: 0.01         # Коэффициент регуляризации весов 